### ISSUE TITLE
Issues with RABBITMQ_ERLANG_COOKIE and permissions

### ISSUE THREAD

**Issue by advancedsei** [jharting/openshift-rabbitmq-cluster#1]
warning: /var/lib/rabbitmq/.erlang.cookie contents do not match RABBITMQ_ERLANG_COOKIE
    
   sed: couldn't open temporary file /etc/rabbitmq/sedRe7mWL: Read-only file system

**Comment by advancedsei** [comment]
Re initialized the PV fixed the cookie issue. but now the issues is the read only file system 

  sed: couldn't open temporary file /etc/rabbitmq/sedRe7mWL: Read-only file system

**Comment by ploef** [comment]
Same error about the Read-Only file system here.
