### ISSUE TITLE
Could not auto-cluster with node 

### ISSUE THREAD

**Issue by vilvamani** [jharting/openshift-rabbitmq-cluster#10]
Hi,

I'm facing below issue while deploying the RabbitMQ cluster in OpenShift 3.9.

**Error:**
2019-03-14 05:09:59.378 [info] <0.266.0> FHC read buffering:  OFF
--
  | 2019-03-14 05:09:59.378 [info] <0.266.0> FHC write buffering: ON
  | 2019-03-14 05:09:59.383 [info] <0.224.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cluster-1.rabbitmq-cluster.xyz-dev.svc.cluster.local is empty. Assuming we need to join an existing cluster or initialise from scratch...
  | 2019-03-14 05:09:59.383 [info] <0.224.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
  | 2019-03-14 05:09:59.383 [info] <0.224.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
  | 2019-03-14 05:09:59.383 [info] <0.224.0> Peer discovery backend does not support locking, falling back to randomized delay
  | 2019-03-14 05:09:59.383 [info] <0.224.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
  | 2019-03-14 05:09:59.405 [info] <0.224.0> All discovered existing cluster peers: rabbit@rabbitmq-cluster-1.rabbitmq-cluster.development.svc.cluster.local, rabbit@rabbitmq-cluster-0.rabbitmq-cluster.development.svc.cluster.local
  | 2019-03-14 05:09:59.405 [info] <0.224.0> Peer nodes we can cluster with: rabbit@rabbitmq-cluster-1.rabbitmq-cluster.development.svc.cluster.local, rabbit@rabbitmq-cluster-0.rabbitmq-cluster.development.svc.cluster.local
  | 2019-03-14 05:09:59.409 [warning] <0.224.0> Could not auto-cluster with node rabbit@rabbitmq-cluster-1.rabbitmq-cluster.development.svc.cluster.local: {badrpc,nodedown}
  | 2019-03-14 05:09:59.419 [warning] <0.224.0> Could not auto-cluster with node rabbit@rabbitmq-cluster-0.rabbitmq-cluster.development.svc.cluster.local: {badrpc,nodedown}
  | 2019-03-14 05:09:59.419 [warning] <0.224.0> Could not successfully contact any node of: rabbit@rabbitmq-cluster-1.rabbitmq-cluster.development.svc.cluster.local,rabbit@rabbitmq-cluster-0.rabbitmq-cluster.development.svc.cluster.local (as in Erlang distribution). Starting as a blank standalone node...
  | 2019-03-14 05:09:59.436 [info] <0.43.0> Application mnesia exited with reason: stopped
  | 2019-03-14 05:10:02.039 [info] <0.224.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
  | 2019-03-14 05:10:02.104 [info] <0.224.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
  | 2019-03-14 05:10:02.210 [info] <0.224.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
  | 2019-03-14 05:10:02.210 [info] <0.224.0> Peer discovery backend

**Comment by maanur** [comment]
The same issue on OpenShift 3.11
